language: ruby
rvm:
- 2.5.0
script:
- bundle exec middleman build --no-parallel
- bundle exec middleman s3_sync
branches:
  only:
  - master
env:
  global:
    secure: ML/eIJ/hLaoLUSbNShkswfn80mDK4QaLC1LnfT2p8tq8Hv1TSUcmckqGi6NUpsa/Rg/+36JrIGZWLIFv7A5wgihy0872vhBndAjEkcXIsvbzkRfv2YP/OEA63KXgchPRdU5XExApi9ps26ZqyOx3pDddHU3HT2zcaxBISWHLw5SsCHDpD4PKink8bKSjC4sT3Yk+nXirQMYYd1i5ECz3nq+q9bzr68w0+AnBiH3cmpddaxLgCT1mdJgjdQk/bcr/t9a1G0nVm2AqxNSz6G7YB0cKtZmkAIPK9cQWLaLtkxmtUmR2FftTjSHiHrVXppKd9Tt1dCNL02EnP9UcuOIVwbmBSJKrm6fJOUEQZ0xyeMvvO5NE7Cv7psXUoSAUFugvIHFvcR0BQhH/PmDXGvA0JVtnr/5kTeNqgNLP2pk2xmXQkYtln1gmLw0mpMUhk1P+vVH3F8fzZzm4UsxKJHzKwMIkHhUE0Dab80mlanO4UEAtEOrZoXXFpD1k5EV3Thl1WVAWn8oi8LrK3WU8ISYuZFed0QHJzHxY7pHTG2BQz7alRXjqrTQDtQYUtn++gV72OhsOpTiUngOYdAKYU7fIvyKUXv1LqAATqMrmDBYrOafKfz/49EjJnbM8xXPdgFruM9iWrpqgh7/rKcep9sRzS8GU11gWLAuGFd6xXL0zikQ=
notifications:
  slack: devxio:JRE2eRz4DXZrWdnzioczQn96
